core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
]

# Admin Site Customization
admin.site.site_header = 'Construction App'
admin.site.site_title = 'Construction App'

dashboard/urls.py
from django.urls import path, include
from .views import projects, users


app_name = 'dashboard'


urlpatterns = [
    # Signup/Register
    path('account/', include('django.contrib.auth.urls')),
    path('account/register', users.register, name='register'),

    # Projects
    path('', projects.index, name='index'),
    path('projects/', projects.ProjectList.as_view(), name='project-list'),
    path('project/<int:pk>', projects.ProjectDetail.as_view(), name='project-detail'),
    path('projects/create/', projects.ProjectCreate.as_view(), name='project-create'),
    path('project/<int:pk>/update/', projects.ProjectUpdate.as_view(), name='project-update')
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse
from django.core.mail import EmailMessage, get_connection
from django.conf import settings
from django.utils import timezone
from model_utils import FieldTracker
from . import utils
from . import managers

import datetime


class Base(models.Model):
    created_at = models.DateTimeField(
        'Created date',
        auto_now_add=True,
        help_text='Record created date and time'
    )
    updated_at = models.DateTimeField(
        'Last updated',
        auto_now=True,
        help_text='Record last updated date and time'
    )

    class Meta:
        abstract = True


class CustomUser(AbstractUser):
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    full_name = models.CharField(max_length=120)
    job_title = models.CharField(max_length=100)
    bio = models.TextField('Short Bio', null=True, blank=True)
    projects_followed = models.ManyToManyField(
        'Project',
        related_name='followers',
        blank=True
    )
    projects_administered = models.ManyToManyField(
        'Project',
        related_name='admins',
        blank=True
    )

    def get_full_name(self):
        return self.full_name

    def get_screen_name(self):
        """
        Returns either the user's full name (if is set) or their username
        """
        if self.full_name:
            return self.get_full_name()
        else:
            return self.username

    def get_notifications(self, *args, **kwargs):
        """
        Returns all notification received by this user instance
        """
        return self.received_notifications.order_by('-created_at')

    def unseen_notifications(self, *args, **kwargs):
        return self.received_notifications.filter(is_seen=False)


class Config(Base):
    """
    Constant configurations and meta data
    """
    CONFIG_TYPE_CHOICES = (
        ('company', 'Company detail configurations'),
        ('website', 'Website configurations'),
        ('other', 'Other configurations'),
    )
    config_type = models.CharField(
        max_length=60,
        choices=CONFIG_TYPE_CHOICES,
    )
    name = models.CharField(max_length=60)
    slug = models.SlugField(max_length=60)
    value = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        ordering = ['config_type', ]
        verbose_name = 'Website Configuration'
        verbose_name_plural = 'Website Configurations'

    def __str__(self):
        return self.name


class Consultant(Base):
    """
    Represents a Consultant Firm
    """
    full_name = models.CharField(
        max_length=100,
        help_text='Official full name of the Consultant firm',
    )
    short_name = models.CharField(
        max_length=100,
        help_text='Short common name of the Consultant firm',
    )
    description = models.TextField(
        null=True, blank=True,
        help_text='Short description of the Consultant firm. (Optional)',
    )

    def __str__(self):
        return self.short_name

    def get_absolute_url(self):
        return reverse('dashboard:consultant-detail', args=[str(self.pk)])


class Notification(Base):
    """
    Represents a Notification
    """
    project = models.ForeignKey(
        'Project',
        related_name='all_notifications',
        on_delete=models.CASCADE,
    )
    triggered_by = models.ForeignKey(
        CustomUser,
        null=True,
        on_delete=models.SET_NULL,
        related_name='triggered_notifications'
    )
    notify_to = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name='received_notifications'
    )
    subject = models.CharField(max_length=120)
    message = models.TextField('Notification message')
    is_seen = models.BooleanField('Seen', default=False)
    seen_date = models.DateTimeField(null=True, blank=True)
    is_email_sent = models.BooleanField('Email Sent Status', default=False)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()

    class Meta:
        ordering = ['-is_seen', '-updated_at', ]
        get_latest_by = ['-updated_at', ]

    def __str__(self):
        return '{} - From {} To {}'.format(
            self.subject,
            self.triggered_by,
            self.notify_to
        )

    def get_email_subject(self, *args, **kwargs):
        """
        Return a 'Subject' for email of this notification
        """
        return self.subject

    def get_email_body(self, *args, **kwargs):
        """
        Returns the 'Body' of the email for this notification
        """
        return self.message

    def get_email_message(self, *args, **kwargs):
        """
        Returns a EmailMessage object
        """
        connection = kwargs.get('connection')
        subject = self.notification.get_email_subject()
        body = self.get_email_body()
        sender = settings.EMAIL_HOST_USER
        recipient_list = [self.notify_to.email, ]
        return EmailMessage(
            subject,
            body,
            sender,
            recipient_list,
            connection=connection
        )

    def send_email(self, *args, **kwargs):
        email_message = self.get_email_message()
        if email_message.send():
            self.is_email_sent = True
            self.save()

    @staticmethod
    def send_unsent_emails(**kwargs):
        triggered_by = kwargs.get('triggered_by')
        notify_to = kwargs.get('notify_to')

        query = Notification.objects.filter(is_email_sent=False)

        if triggered_by:
            query = query.filter(triggered_by=triggered_by)

        if notify_to:
            query = query.filter(notify_to=notify_to)

        for notification in query:
            notification.send_email()


class Activity(Base):
    """
    Represents construction Activity
    Example: Earth works, Concrete Work, Finishing Work
    """
    title = models.CharField('Construction Activity', max_length=60)
    description = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['title', 'updated_at', ]
        verbose_name = 'Construction Activity'
        verbose_name_plural = 'Construction Activities'

    def __str__(self):
        return self.title


class Project(Base):
    """
    Represents a Construction Project
    """
    CONSTRUCTION_TYPE_CHOICES = (
        ('builiding', 'Buildings and Structures'),
        ('road', 'Road and Highway'),
        ('water', 'Water and Irrigations'),
    )
    PROJECT_STATUS_CHOICES = (
        (1, 'Unknown'),
        (2, 'Mobilization'),
        (3, 'Active'),
        (4, 'Rectification'),
        (5, 'Suspended'),
        (6, 'Terminated'),
        (7, 'Closed'),
    )
    construction_type = models.CharField(
        max_length=60,
        choices=CONSTRUCTION_TYPE_CHOICES,
        default='builiding'
    )
    status = models.IntegerField(
        'Project Status',
        choices=PROJECT_STATUS_CHOICES,
        default=1,
    )
    consultant = models.ForeignKey(Consultant, on_delete=models.CASCADE)
    employer = models.CharField(
        max_length=100,
        help_text='Official full name of the Employer',
    )
    full_name = models.CharField(
        'Official Project Title',
        max_length=100,
        help_text='Official full name of the construction project',
    )
    short_name = models.CharField(
        'Short Unofficial Project Title',
        max_length=100,
        help_text='Short common name of the construction project',
    )
    project_code = models.CharField(
        'Project Code (Optional)',
        max_length=30,
        null=True, blank=True,
    )
    description = models.TextField(
        'Short Project Description',
        null=True, blank=True,
        help_text='Short description of the construction project. (Optional)',
    )
    contract_amount = models.DecimalField(
        max_digits=16, decimal_places=2,
        help_text='Project contract amount in ETB (before VAT)',
    )
    signing_date = models.DateField(
        'Agreement Signing Date',
        null=True, blank=True,
    )
    site_handover = models.DateField(
        'Site Handover Date',
        null=True, blank=True,
    )
    commencement_date = models.DateField('commencement Date')
    period = models.PositiveIntegerField(
        'Contract Period',
        help_text='Project life time in calendar days'
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='projects',
        on_delete=models.SET(utils.get_phantom_user),
    )
    notifications = GenericRelation(Notification)

    # Field Tracker module
    tracker = FieldTracker()

    # Custom Managers
    objects = models.Manager()
    my_projects = managers.ProjectManager()

    class Meta:
        ordering = ['status', '-updated_at', 'short_name', ]
        get_latest_by = 'updated_at'
        permissions = (
            ('admin_project', 'Administer Project'),
        )

    def __str__(self):
        return self.short_name

    def get_absolute_url(self):
        return reverse('dashboard:project-detail', args=[str(self.pk)])

    @property
    def completion_date(self, *args, **kwargs):
        """
        Returns the project completion date
        """
        return self.commencement_date + datetime.timedelta(days=self.period)

    def get_days_left(self, *args, **kwargs):
        """
        Returns the number of days left to project completion date in
        calendar days
        """
        return (self.completion_date - timezone.localdate()).days

    def add_notification(self, subject, message, notify_to, *args, **kwargs):

dashboard/views/projects.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from dashboard import models

from dashboard import forms

from dashboard import utils


@login_required
def index(request):
    template_name = 'dashboard/index.html'
    return render(request, template_name, {
        'page_name': 'index',
    })


class ProjectList(LoginRequiredMixin, generic.ListView):
    """
    List all published projects
    """
    model = models.Project
    template_name = 'dashboard/projects/project_list.html'

    def get_queryset(self, *args, **kwargs):
        return self.model.my_projects.all().order_by('status')

    def get(self, request, *args, **kwargs):
        subscription = request.GET.get('subscription')
        if subscription:
            pk = int(request.GET['project'])
            project = get_object_or_404(models.Project, pk=pk)
            if subscription == 'follow':
                project.followers.add(request.user)
                project.save()
                project.add_notification(
                    subject='You started following a new project',
                    message='You started following {} project'.format(
                        project.short_name
                    ),
                    notify_to=request.user
                )
                return redirect('dashboard:project-list')

            if subscription == 'unfollow':
                project.followers.remove(request.user)
                project.save()
                return redirect('dashboard:project-list')
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super(ProjectList, self).get_context_data(*args, **kwargs)
        context['page_name'] = 'Projects'
        return context


class ProjectDetail(LoginRequiredMixin, generic.DetailView):
    """
    Display  a single published project
    """
    model = models.Project
    template_name = 'dashboard/projects/project_detail.html'

    def get_context_data(self, *args, **kwargs):
        # Change unseen notification to seen
        unseen_notifications = self.object.notifications.filter(
            notify_to=self.request.user
        ).filter(is_seen=False)

        for notification in unseen_notifications:
            notification.is_seen = True
            notification.save()

        context = super(ProjectDetail, self).get_context_data(*args, **kwargs)
        context['page_name'] = 'Projects'
        return context


class ProjectCreate(LoginRequiredMixin, UserPassesTestMixin, generic.CreateView):
    """
    Create a new project record
    """
    form_class = forms.ProjectForm
    model = models.Project
    template_name = 'dashboard/projects/project_form.html'
    success_message = 'New project created successfully.'

    def test_func(self, *args, **kwargs):
        return self.request.user.has_perms('dashboard.admin_project')

    def get_context_data(self, *args, **kwargs):
        context = super(ProjectCreate, self).get_context_data(*args, **kwargs)
        context['page_name'] = 'Projects'
        return context


class ProjectUpdate(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    """
    Update an existing project record
    """
    form_class = forms.ProjectForm
    model = models.Project
    template_name = 'dashboard/projects/project_form.html'
    success_message = 'Project updated successfully.'

    def test_func(self, *args, **kwargs):
        return self.request.user.has_perms('dashboard.admin_project')

    def get_context_data(self, *args, **kwargs):
        context = super(ProjectUpdate, self).get_context_data(*args, **kwargs)
        context['page_name'] = 'Projects'
        return context

dashboard/views/users.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from dashboard import forms

from dashboard import models


def register(request):
    """
    Register a new user, login the new user and redirect to
    breakdowns:index page
    """

    # Check if user already logged
    if request.user.is_authenticated:
        return redirect('dashboard:index')

    form_class = forms.SignupForm
    template_name = 'registration/register.html'

    if request.method == 'POST':
        form = form_class(request.POST)

        if form.is_valid():
            full_name = form.cleaned_data.get('full_name')
            email = form.cleaned_data.get('email')
            job_title = form.cleaned_data.get('job_title')
            form.save()
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1']
            )
            user.full_name = full_name
            user.email = email
            user.job_title = job_title
            user.is_active = False
            user.save()
            # messages.success(
            #     request,
            #     'You have successfully created a new account.'
            # )
            # messages.warning(
            #     request,
            #     ('Your account must be activated before you can start '
            #      'using it. Please contact the admin to quickly activate '
            #      'your account.')
            # )
                
            return redirect('dashboard:index')
    else:
        form = form_class()
    return render(request, template_name, {
        'form': form,
    })

dashboard/templates/dashboard/projects/project_detail.html
{% extends 'dashboard_base.html' %}
{% load static %}

{% block content %}
   {{ project }}
   <br>
   {{ project.signing_date }}
   <br>
   {{ project.commencement_date|date:'m/d/y' }}
{% endblock content %}

dashboard/templates/dashboard/projects/project_list.html
{% extends 'dashboard_base.html' %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <div class="card">
          <div class="card-header card-header-primary card-header-icon">
            <div class="card-icon">
              <i class="material-icons">assignment</i>
            </div>
            <h4 class="card-title">All Projects</h4>
          </div>
            <div class="card-body">
                <div class="toolbar">
                    <!--        Here you can write extra buttons/actions for the toolbar              -->
                </div>
                <div class="material-datatables">
                    <table id="projectDatatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                        <thead>
                            <tr>
                                <th>Status</th>
                                <th>Project</th>
                                <th>Type</th>
                                <th class="text-center">Last Updated</th>
                                <th class="disabled-sorting text-right">Actions</th>
                            </tr>
                        </thead>
                        <!-- <tfoot>
                            <tr>
                                <th>Status</th>
                                <th>Project</th>
                                <th>Type</th>
                                <th class="text-center">Last Updated</th>
                                <th class="text-right">Actions</th>
                            </tr>
                        </tfoot> -->
                        <tbody>
                            {% for project in project_list %}
                            <tr>
                                <td>
                                    {% autoescape off %}
                                    {{ project.get_status_label }}
                                    {% endautoescape %}
                                </td>
                                <td>
                                    <a href="{% url 'dashboard:project-detail' project.id %}" title="{{ project.full_name }}">{{ project.short_name }}</a>
                                </td>
                                <td>{{ project.get_construction_type_display }}</td>
                                <td class="text-center">{{ project.updated_at|date:'d/m/Y' }}</td>
                                <td class="text-right">
                                    {% if project in user.projects_followed.all %}
                                    <form>
                                        <input type="hidden" name="project" value="{{ project.id }}">
                                        <input type="hidden" name="subscription" value="unfollow">
                                        <button type="submit" class="btn btn-sm btn-primary">Unfollow</button>
                                    </form>
                                    {% else %}
                                    <form>
                                        <input type="hidden" name="project" value="{{ project.id }}">
                                         <input type="hidden" name="subscription" value="follow">
                                        <button type="submit" class="btn btn-sm btn-outline btn-primary">&nbsp;&nbsp;Follow&nbsp;&nbsp;</button>
                                    </form>
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div><!-- end content-->
        </div><!--  end card  -->
    </div>
</div><!-- /.row -->

{% if user.is_project_admin %}
<div class="row">
    <div class="col-sm-12">
        <a href="{% url 'dashboard:project-create' %}" title="Add new project" class="btn btn-sm btn-outline btn-primary pull-right">
           <span class="fa fa-plus-circle"></span>&nbsp; New Project 
        </a>
    </div>
</div>
{% endif %}
{% endblock content %}